version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: contract-management
        ports:
            - 5432:5432
        restart: always
    contract-management-api:
        build: .
        ports: 
            - 8080:8080
        links:
            - postgres:postgres
        depends_on: 
            - postgres